# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d07483e5b746c168e6b96eb92a4745bd526aa886b5fab66f7d5d5ac91b3bf24af726e5b34968dd369ca393ecba01193468bc8c1d9b3c20e76582cb5ab3149eaf

test:
  secret_key_base: b5a2c74640491fb335d98499bfd558ae9db2ba55d07718de9da76d8cb626333215bbad9bd28e6013aee5e9895f9f3c657a98a28677bc8e75088d9dfef15d4d7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
